language: node_js
node_js:
- '13.5.0'

install:
  - npm run setup
  - npm install
  - cd ./test && rm -rf node_modules/yaml && npm i yaml@1.7.2 && cd ../

script:
  - npm test
  # - ls -l
  # - cd ./test && ls -l && npm run node