name: Autotag

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: butlerlogic/action-autotag@master
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        ACTIONS_STEP_DEBUG: true
